# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LayeredCode < Formula
  desc "Homebrew tap for layered-code"
  homepage "https://github.com/layered-flow/layered-code"
  version "0.0.7"
  license "MIT"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/layered-flow/layered-code/releases/download/v0.0.7/layered-code_Darwin_x86_64.tar.gz"
      sha256 "ad68193fed41f2ea59e2268e4621bff3259ae3b0aca0886d5fdfc5e4dfe9cd9d"

      def install
        bin.install "layered-code"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/layered-flow/layered-code/releases/download/v0.0.7/layered-code_Darwin_arm64.tar.gz"
      sha256 "4681025bd966f7f8ff0f1d7fb4ccc0624a1e4b26f6739dc362e005d7589299b7"

      def install
        bin.install "layered-code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/layered-flow/layered-code/releases/download/v0.0.7/layered-code_Linux_x86_64.tar.gz"
      sha256 "1fa548d9dd1ed97174cc8fab1765b9181c2fd0c0376296b520f076f574886e5c"
      def install
        bin.install "layered-code"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/layered-flow/layered-code/releases/download/v0.0.7/layered-code_Linux_arm64.tar.gz"
      sha256 "efb18e79d0a55de0d8babb7ea9f83a9c69aedde4fbc6ce8bcfb26c29f2f84e74"
      def install
        bin.install "layered-code"
      end
    end
  end

  test do
    system "#{bin}/layered-code", "--help"
  end
end
