# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LayeredCode < Formula
  desc "Homebrew tap for layered-code"
  homepage "https://github.com/layered-flow/layered-code"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/layered-flow/layered-code/releases/download/v0.0.3/layered-code_Darwin_x86_64.tar.gz"
      sha256 "af7c17f24f85206deabc2b3e680a75c8aaf4f47bfb7d7c244f9f7407e11082dc"

      def install
        bin.install "layered-code"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/layered-flow/layered-code/releases/download/v0.0.3/layered-code_Darwin_arm64.tar.gz"
      sha256 "e486f3c1d5d6eadb74884d3b7d959a4f62355f20b3de448d1b7a8985cf0167cd"

      def install
        bin.install "layered-code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/layered-flow/layered-code/releases/download/v0.0.3/layered-code_Linux_x86_64.tar.gz"
      sha256 "a0423540d2379700cd60052a995204f7a4a06f6d4cc8c4ea98813aaeca140f1c"
      def install
        bin.install "layered-code"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/layered-flow/layered-code/releases/download/v0.0.3/layered-code_Linux_arm64.tar.gz"
      sha256 "ed4773e44e959fbf3f9fe5a479ca14e0a9eccdb3bf3bee413813290f2130dc71"
      def install
        bin.install "layered-code"
      end
    end
  end

  test do
    system "#{bin}/layered-code", "--help"
  end
end
